spring:
  application:
    name: configserver

  cloud:
    config.server.git:
      uri: https://github.com/ajay-nakkani/lovable-config-server.git
      username: ajay-nakkani
      password: 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
      default-label: main


server.port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    config:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: k8s

  cloud:
    discovery:
      enabled: false
    config.server.git:
      uri: https://github.com/ajay-nakkani/lovable-config-server.git
      username: ${GIT_USERNAME}
      password: ${GIT_PASSWORD}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false